markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
    - jekyll-octicons

title: KF6010
subtitle: Distributed real-time systems
authors: David Kendall, Alun Moon
copyyear: 2018
url: http://hesabu.net
baseurl: /kf6010
raurl: /assets/ra
rraurl: /assets/ra
#url: http://localhost:4000
#raurl: http://localhost:4000/assets/ra

lab_links:
   - title: Lab 1 
     url: L01.html
     #rep: blinky
   - title: Lab 2 
     url: L02.html
     #rep: blinky
   - title: Lab 3 
     url: L03.html
     #rep: buttons
   - title: Lab 4 
     url: L04.html
     #rep: interrupt
   - title: Lab 5 
     url: L05.html
     #rep: tasks
   - title: Lab 6 
     url: L06.html
     #rep: peterson
   - title: Lab 7 
     url: L07.html
     #rep: semaphore
   - title: Lab 8 
     url: L08.html
     #rep: ringbuffer
   - title: Lab 9 
     url: L09.html
     #rep: deadlock
   - title: Lab 10 
     url: L10.html
     #rep: blinky
   - title: Lab 11 
     url: assets/ra/L11.pdf
     #rep: blinky
   - title: Lab 12
     url: assets/ra/L12.pdf
   - title: Lab 13
     url: M01.html
   - title: Lab 14
     url: M02.html
   - title: Lab 15
     url: M03.html
   - title: Lab 16
     url: M04.html
   - title: Lab 17
     url: M05.html
   - title: Lab 18
     url: M06.html
   - title: Lab 19
     url: M07.html
   - title: Lab 20
     url: M08.html
   - title: Lab 21
     url: M09.html
   - title: Lab 22
     url: M10.html
   - title: Lab 23
     url: M11.html

#right_links:
  #- title: View on GitHub
    #url: https://github.com/davidkendall/kf4005

#repo: https://github.com/davidkendall/kf6010
